name: techara_merchant
description: "A new Flutter project for Techara Merchant App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

 #localization 
  flutter_localization: ^0.3.2
  intl: ^0.20.2

# Networking
  mime: ^1.0.0
  http_parser: ^4.0.1
  dio: ^5.8.0+1
  retrofit: ^4.7.0

#icons
  cupertino_icons: ^1.0.2

#statemanagment
  flutter_bloc: ^8.1.1
  dropdown_button2: ^2.0.0
  pinput: ^2.2.31
  injectable: ^2.3.0
  freezed_annotation: ^3.1.0

#widget  
  flutter_svg: ^2.0.10+1
  modal_bottom_sheet: ^3.0.0
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1


 #hardware
 
 

 #localdatabase 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  

 #others
  
  path_provider: ^2.0.11
  provider: ^6.0.0
  file_picker: ^8.3.1

  get_it: ^7.6.4
  image_cropper: ^9.1.0

  phosphor_flutter: ^2.1.0
  json_annotation: ^4.9.0
  dart_mappable: ^4.6.0
  image_picker: ^1.1.2
  flutter_inappwebview: ^6.1.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0
  freezed: ^3.2.0
  # swagger_to_dart: ^3.2.1
  swagger_parser: ^1.28.0
  retrofit_generator: ^10.0.1
  dart_mappable_builder: ^4.6.0
  
  


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/fonts/noto/
    - assets/fonts/somar/
   


    

  fonts:
   
    - family: Somar
      fonts:
       
      
        - asset: assets/fonts/somar/SomarRounded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/somar/SomarRounded-Bold.ttf
          weight: 700
       
        - asset: assets/fonts/somar/SomarRounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/somar/SomarRounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/somar/SomarRounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/somar/SomarRounded-Light.ttf
          weight: 300
        - asset: assets/fonts/somar/SomarRounded-ExtraLight.ttf
          weight: 200     
        - asset: assets/fonts/somar/SomarRounded-Thin.ttf
          weight: 100     

    - family: Noto
      fonts:
       
      
        - asset: assets/fonts/noto/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto/NotoSans-SemiBold.ttf
          weight: 600
       
        - asset: assets/fonts/noto/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto/NotoSans-Light.ttf
          weight: 300
         
       
      